version: '1'
services:
  melita-io-egress:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: melita-io-egress
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
      EGRESS_URL: https://hookb.in/example
      EXECUTE_SINGLE_COMMAND: no
      SINGLE_COMMAND: addDownlinkDeviceQueue
      AUTHENTICATION_API_KEY:
      ERROR_URL: https://hookb.in/example
      MELITA_API_URL: https://www.melita.io/api/iot-gateway
      ports:
        - 5000:80
