version: "3.0"
services:
  melita-io-egress:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "melita-io-egress"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EXECUTE_SINGLE_COMMAND: 'no'
      SINGLE_COMMAND: ''
      MELITA_API_URL: 'https://www.melita.io/api/iot-gateway'
      AUTHENTICATION_API_KEY: ''
      ERROR_URL: ''
    ports:
      - 80:80
